# Завдання 1

## Вправа 1

Вводиться число n. Вивести масив розміру n×n, в
якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0. 

In [8]:
def task_1():
    n = int(input("Enter n: "))
    arr = [[0 for j in range(n)] for i in range(n)]
    
    for i in range(n):
        arr[i][i] = i + 1

    for row in arr:
        print(row)
        
        
%time task_1()

Enter n: 4
[1, 0, 0, 0]
[0, 2, 0, 0]
[0, 0, 3, 0]
[0, 0, 0, 4]
CPU times: user 5.79 ms, sys: 3.59 ms, total: 9.38 ms
Wall time: 326 ms


In [2]:
import numpy as np

def task_1():
    n = int(input("Enter n: "))
    arr = np.zeros((n, n), dtype=int)
    arr[np.diag_indices_from(arr)] = np.arange(1, n+1)
    print(arr)


%time task_1()

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
CPU times: user 567 ms, sys: 18.1 ms, total: 585 ms
Wall time: 4.99 s


## Вправа 3

Вводяться 4 числа n, m, r, c. Вивести масив розміру n×m, в якому в кожному рядку з номером r і в кожному стовпчику з номером c стоять 0, а інші елементи дорівнюють 1.

In [3]:
def task_3():
    n = int(input("Enter n: "))
    m = int(input("Enter m: "))
    r = int(input("Enter r: "))
    c = int(input("Enter c: "))
    
    arr = [[1 for j in range(m)] for i in range(n)]
    
    for i in range(n):
        if i % r == 0:
            arr[i] = [0 for j in range(m)]

    for i in range(m):
        if i % c == 0:
            for j in range(n):
                arr[j][i] = 0
        
    for row in arr:
        print(row)
        
%time task_3()
    

[1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1]
CPU times: user 69 ms, sys: 38.1 ms, total: 107 ms
Wall time: 9.06 s


In [12]:
import numpy as np

def task_3():
    n = int(input("Enter n: "))
    m = int(input("Enter m: "))
    r = int(input("Enter r: "))
    c = int(input("Enter c: "))
    
    arr = np.ones((n, m), dtype=int)
    arr[::r, :] = 0
    arr[:, ::c] = 0

    print(arr)
    
%time task_3()

Enter n: 6
Enter m: 7
Enter r: 2
Enter c: 3
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]
CPU times: user 59.9 ms, sys: 36.7 ms, total: 96.6 ms
Wall time: 5.49 s


## Вправа 4

Вводяться числа n і m. Вивести масив розміру n×m, в якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0 до m–1, а всі інші елементи матриці дорівнюють 0.

In [17]:
def task_4():
    n = int(input("Enter n: "))
    m = int(input("Enter m: "))
    
    arr = [[0 for j in range(m)] for i in range(n)]
    
    for i in range(m):
        arr[0][i] = i
        
    for row in arr:
        print(row)
        
%time task_4()

Enter n: 3
Enter m: 4
[0, 1, 2, 3]
[0, 0, 0, 0]
[0, 0, 0, 0]
CPU times: user 12.3 ms, sys: 6.23 ms, total: 18.5 ms
Wall time: 970 ms


In [2]:
import numpy as np

def task_4():
    n = int(input("Enter n: "))
    m = int(input("Enter m: "))
    
    arr = np.zeros((n, m), dtype=int)
    
    arr[0] = np.arange(m)
    
    print(arr)
    
%time task_4()

Enter n: 3
Enter m: 4
[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]
CPU times: user 14.3 ms, sys: 4.96 ms, total: 19.3 ms
Wall time: 1.14 s


## Вправа 5

Вводиться число n. Вивести масив розміру n×n, в якому в рядках з парними індексами стоять 1, а в інших – 0.

In [128]:
def task_5():
    n = int(input("Enter n: "))
    
    arr = [[0 for j in range(n)] for i in range(n)]
    
    for i in range(n):
        if i % 2 == 0:
            for j in range(n):
                arr[i][j] = 1
                
    for row in arr:
        print(row)
        
%time task_5()

Enter n: 10
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
CPU times: user 17.2 ms, sys: 8.19 ms, total: 25.4 ms
Wall time: 1.14 s


In [129]:
import numpy as np

def task_5():
    n = int(input("Enter n: "))
    
    arr = np.zeros((n, n), dtype=int)
    arr[::2] = np.ones(n, dtype=int)
    
    print(arr)
    
%time task_5()

Enter n: 10
[[1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]]
CPU times: user 11.9 ms, sys: 8.52 ms, total: 20.4 ms
Wall time: 643 ms


## Вправа 10

Вводиться числа n i m. Створити масив випадкових значень n×m і обчислити мінімальне, максимальне значення, середнє та середньо квадратичне відхилення, округлене до 3 знаків після коми.

In [14]:
import random
import math

def task_10():
    n = int(input("Enter n: "))
    m = int(input("Enter m: "))
    
    arr = [[round(random.uniform(0, 1), 3) for j in range(m)] for i in range(n)]

    arr_min = min(min(arr[i]) for i in range(n))
    arr_max = max(max(arr[i]) for i in range(n))

    sum_val = sum(sum(arr[i]) for i in range(n))
    arr_mean = sum_val / (n * m)

    sq_diff = sum((arr[i][j] - arr_mean) ** 2 for i in range(n) for j in range(m))
    arr_std = math.sqrt(sq_diff / (n * m))

    print(f"мінімум: {arr_min}")
    print(f"максимум: {arr_max}")
    print(f"середнє: {arr_mean:.3f}")
    print(f"дисперсія: {arr_std:.3f}")

%time task_10()

Enter n: 3
Enter m: 4
мінімум: 0.049
максимум: 0.973
середнє: 0.583
дисперсія: 0.283
CPU times: user 13.1 ms, sys: 7.2 ms, total: 20.3 ms
Wall time: 1.05 s


In [15]:
import random
import math
import numpy as np

def task_4():
    n = int(input("Enter n: "))
    m = int(input("Enter m: "))
    
    arr = np.random.rand(n, m)
    arr_min = np.min(arr)
    arr_max = np.max(arr)
    arr_mean = np.mean(arr)
    arr_std = np.std(arr)
    
    print(f"мінімум: {arr_min}")
    print(f"максимум: {arr_max}")
    print(f"середнє: {arr_mean:.3f}")
    print(f"дисперсія: {arr_std:.3f}")
    
%time task_10()    

Enter n: 3
Enter m: 4
мінімум: 0.112
максимум: 0.915
середнє: 0.520
дисперсія: 0.252
CPU times: user 11.7 ms, sys: 5.85 ms, total: 17.6 ms
Wall time: 833 ms


## Вправа 12

Створити масив одиниць розміром n×n та створити в ньому «рамку», що утворюється з 0.

In [22]:
def task_12():
    n = int(input("Enter n: "))
    
    arr = [[1 for j in range(n)] for i in range(n)]
    
    arr[0] = [0 for i in range(n)]
    arr[n-1] = [0 for i in range(n)]
    
    for i in range(1, n-1):
        for j in range(n):
            if j == 0 or j == n - 1:
                arr[i][j] = 0
                
    for row in arr:
        print(row)
        
%time task_12()
    

Enter n: 6
[0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 0, 0, 0, 0, 0]
CPU times: user 6.85 ms, sys: 4.39 ms, total: 11.2 ms
Wall time: 564 ms


In [32]:
import numpy as np

def task_12():
    n = int(input("Enter n: "))
    
    arr = np.ones((n, n), dtype=int)
    
    arr[::n-1, :] = 0
    arr[:, ::n-1] = 0

    print(arr)
    
%time task_12()

Enter n: 4
[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]
CPU times: user 8.41 ms, sys: 5.02 ms, total: 13.4 ms
Wall time: 573 ms


## Вправа 16

Заповнити вектор значеннями від 0 до n. Всі значення, що більші за n/4 та менші за 3n/4 замінити нулями.

In [35]:
def task_16():
    n = int(input("Enter n: "))
    
    arr = [i for i in range(n+1)]
    
    for i in range(n+1):
        if n/4 < i and i < 3*n/4:
            arr[i] = 0
            
    print(arr)
        
%time task_16()

Enter n: 10
[0, 1, 2, 0, 0, 0, 0, 0, 8, 9, 10]
CPU times: user 10.5 ms, sys: 6.35 ms, total: 16.9 ms
Wall time: 1.16 s


In [37]:
import numpy as np

def task_16():
    n = int(input("Enter n: "))
    
    arr = np.arange(n+1)
    arr[(arr > n/4) & (arr < 3*n/4)] = 0
    
    print(arr)
    
%time task_16()

Enter n: 10
[ 0  1  2  0  0  0  0  0  8  9 10]
CPU times: user 14.1 ms, sys: 7.75 ms, total: 21.8 ms
Wall time: 1.42 s


## Вправа 17

Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх значень, що менші за n/2 та більші за 3n/4 на протилежні.

In [43]:
def task_17():
    n = int(input("Enter n: "))
    
    arr = [i for i in range(n+1)]
    
    for i in range(n+1):
        if i < n/2 or i > 3*n/4:
            arr[i] *= -1
            
    print(arr)
        
%time task_17()

Enter n: 10
[0, -1, -2, -3, -4, 5, 6, 7, -8, -9, -10]
CPU times: user 11.5 ms, sys: 6.44 ms, total: 17.9 ms
Wall time: 1.18 s


In [46]:
import numpy as np

def task_17():
    n = int(input("Enter n: "))
    
    arr = np.arange(n+1)
    arr[(arr < n/2) | (arr > 3*n/4)] *= -1
    
    print(arr)
    
%time task_17()

Enter n: 10
[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]
CPU times: user 9.26 ms, sys: 6.93 ms, total: 16.2 ms
Wall time: 1.04 s


## Вправа 21

Ввести числа n і m. Згенерувати матрицю n×n випадкових цілих елементів з діапазону [0, m]. Замінити всі максимальні елементи цієї матриці на протилежні за знаком.

In [52]:
def task_21():
    n = int(input("Enter n: "))
    m = int(input("Enter m: "))
    
    arr = [[random.randint(0, m) for j in range(n)] for i in range(n)]
    
    print('Початковий вектор')
    for row in arr:
        print(row)
        
    arr_max = max(max(arr[i]) for i in range(n))
    for i in range(n):
        for j in range(n):
            if arr[i][j] == arr_max:
                arr[i][j] *= -1
                
    print('Змінений вектор')
    for row in arr:
        print(row)
        
%time task_21()

Enter n: 4
Enter m: 10
Початковий вектор
[9, 6, 8, 5]
[2, 2, 0, 9]
[7, 9, 9, 3]
[10, 0, 1, 1]
Змінений вектор
[9, 6, 8, 5]
[2, 2, 0, 9]
[7, 9, 9, 3]
[-10, 0, 1, 1]
CPU times: user 22.4 ms, sys: 11.9 ms, total: 34.3 ms
Wall time: 2.32 s


In [56]:
import numpy as np

def task_21():
    n = int(input("Enter n: "))
    m = int(input("Enter m: "))
    
    arr = np.random.randint(0, m+1, size=(n, n))
    
    print('Початковий вектор')
    print(arr)
        
    arr_max = np.max(arr)
    
    arr[arr == arr_max] *= -1
                
    print('Змінений вектор')
    print(arr)
        
%time task_21()

Enter n: 4
Enter m: 9
Початковий вектор
[[3 3 5 1]
 [9 9 8 9]
 [9 5 9 4]
 [1 6 6 9]]
Змінений вектор
[[ 3  3  5  1]
 [-9 -9  8 -9]
 [-9  5 -9  4]
 [ 1  6  6 -9]]
CPU times: user 20 ms, sys: 10.2 ms, total: 30.2 ms
Wall time: 2.12 s


# Завдання 2

Розв'язати систему алгебраїчних рівнянь за допомогою формул Крамера і виконати перевірку за допомогою:
* матричного множення;
* оберненої матриці;
* функції `numpy.linalg.solve()`.

Порівняти всі рішення за допомогою функції `numpy.allclose()`.

Матричне представлення системи лінійних алгебраїчних рівнянь та розв'язок:

In [61]:
A = [[2, -1, 3, 2],
    [3,  3,  3, 2],
    [3, -1, -1, 2],
    [3, -1, 3, -1]]

B = [4, 6, 6, 6]

S = [2, 0, 0, 0]

print('Матриця коефіцієнтів')
for row in A:
    print(row)
    
print('\nВектор вільних членів')
print(B)


print("\nВектор розв'язку")
print(S)

Матриця коефіцієнтів
[2, -1, 3, 2]
[3, 3, 3, 2]
[3, -1, -1, 2]
[3, -1, 3, -1]

Вектор вільних членів
[4, 6, 6, 6]

Вектор розв'язку
[2, 0, 0, 0]


## Перевірка

### Спосіб 1: матричне множення

In [67]:
A = [[2, -1, 3, 2],
    [3,  3,  3, 2],
    [3, -1, -1, 2],
    [3, -1, 3, -1]]

B = [4, 6, 6, 6]

S = [2, 0, 0, 0]

fact_sol = [0] * 4

for i in range(4):
    sum = 0
    for j in range(4):
        sum += A[i][j] * S[j]
    fact_sol[i] = sum
    
print("А * S:")
print(fact_sol)

print("\nA * S == B:")
print(fact_sol == B)

А * S:
[4, 6, 6, 6]

A * S == B:
True


### Спосіб 2: обернена матриця

In [126]:
import numpy as np

A = np.array([[2, -1, 3, 2],
    [3,  3,  3, 2],
    [3, -1, -1, 2],
    [3, -1, 3, -1]])

B = np.array([4, 6, 6, 6])
S = np.array([2, 0, 0, 0])

A_inv = np.linalg.inv(A)


print("inverse A:")
print(A_inv)

fact_sol = A_inv.dot(B)

print("\nA_inv * B:")
print(fact_sol)

print("\nnp.allclose(S, fact_sol):")
print(np.allclose(S, fact_sol))

inverse A:
[[-0.18181818  0.06818182  0.20454545  0.18181818]
 [-0.20454545  0.23295455 -0.05113636 -0.04545455]
 [ 0.20454545  0.01704545 -0.19886364  0.04545455]
 [ 0.27272727  0.02272727  0.06818182 -0.27272727]]

A_inv * B:
[2.00000000e+00 0.00000000e+00 0.00000000e+00 2.22044605e-16]

np.allclose(S, fact_sol):
True


## Розв'язання з використанням `numpy.linalg.solve()`

In [127]:
import numpy as np

A = np.array([[2, -1, 3, 2],
    [3,  3,  3, 2],
    [3, -1, -1, 2],
    [3, -1, 3, -1]])

B = np.array([4, 6, 6, 6])
S = np.array([2, 0, 0, 0])

fact_sol = np.linalg.solve(A, B)


print("np.linarg.solve(A,B):")
print(fact_sol)

print("\nnp.allclose(S, fact_sol):")
print(np.allclose(S, fact_sol))

np.linarg.solve(A,B):
[ 2. -0.  0. -0.]

np.allclose(S, fact_sol):
True


# Завдання 3

Обчислити значення матричного виразу
* з використанням універсальних функцій бібліотеки NumPy.
* за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).
* для обох випадків підрахувати час виконання скрипту та зробити висновок.

Порівняти всі рішення за допомогою функції `numpy.allclose()`.

## Спосіб 1: numpy

In [125]:
import numpy as np

def task_3():
    A = np.array([[3, 2, -5], [4, 2, 0], [1, 1, 2]])
    B = np.array([[-1, 2, 4], [0, 3, 2], [-1, -3, 4]])

    # (A - B)A + 3B
    C = np.add(np.subtract(A, B).dot(A), np.multiply(B, 3))

    print("A:")
    print(A)
    print("\nB:")
    print(B)
    print("\n(A - B)A + 3B:")
    print(C)

%time task_3()

A:
[[ 3  2 -5]
 [ 4  2  0]
 [ 1  1  2]]

B:
[[-1  2  4]
 [ 0  3  2]
 [-1 -3  4]]

(A - B)A + 3B:
[[  0   5 -26]
 [  6  13 -18]
 [ 17   1  -2]]
CPU times: user 994 µs, sys: 639 µs, total: 1.63 ms
Wall time: 1.54 ms


In [124]:
def matr_mul_num(A, n):
    res = [[0 for i in range(3)] for j in range(3)]
    
    for i in range(3):
        for j in range(3):
            res[i][j] = A[i][j] * n
        
    return res

def matr_add(A, B):
    res = [[0 for i in range(3)] for j in range(3)]
    
    for i in range(3):
        for j in range(3):
            res[i][j] = A[i][j] + B[i][j]
    
    return res;

def matr_sub(A, B):
    return matr_add(A, matr_mul_num(B, -1))

def matr_mul(A, B):
    res = [[0 for i in range(3)] for j in range(3)]
    
    for i in range(3):
        for j in range(3):
            for k in range(3):
                res[i][j] += A[i][k] * B[k][j]
    
    return res;

def task_3():
    A = [[3, 2, -5], [4, 2, 0], [1, 1, 2]]
    B = [[-1, 2, 4], [0, 3, 2], [-1, -3, 4]]
    
    res = matr_add(matr_mul(matr_sub(A, B), A), matr_mul_num(B, 3))
    
    print("A:")
    for row in A:
        print(row)
    
    print("\nB:")
    for row in B:
        print(row)
    
    print("\n(A - B)A + 3B:")
    for row in res:
        print(row)
    
%time task_3()

A:
[3, 2, -5]
[4, 2, 0]
[1, 1, 2]

B:
[-1, 2, 4]
[0, 3, 2]
[-1, -3, 4]

(A - B)A + 3B:
[0, 5, -26]
[6, 13, -18]
[17, 1, -2]
CPU times: user 260 µs, sys: 58 µs, total: 318 µs
Wall time: 295 µs
